/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'id' : bigint,
  'requiredDocuments' : Array<string>,
  'name' : string,
  'description' : string,
  'processSteps' : Array<string>,
  'category' : string,
  'estimatedTime' : string,
  'feesInfo' : string,
}
export interface Service {
  'id' : bigint,
  'pricingInfo' : string,
  'requiredDocuments' : Array<string>,
  'name' : string,
  'description' : string,
  'processSteps' : Array<string>,
  'category' : string,
  'timeline' : string,
}
export interface StudyNote {
  'id' : bigint,
  'keySections' : Array<string>,
  'title' : string,
  'notesContent' : string,
  'subject' : string,
  'syllabusOutline' : Array<string>,
  'description' : string,
}
export interface _SERVICE {
  'filterDocumentsByCategory' : ActorMethod<[string], Array<Document>>,
  'filterServicesByCategory' : ActorMethod<[string], Array<Service>>,
  'getDocumentById' : ActorMethod<[bigint], Document>,
  'getServiceById' : ActorMethod<[bigint], Service>,
  'getStudyNoteById' : ActorMethod<[bigint], StudyNote>,
  'listDocuments' : ActorMethod<[], Array<Document>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'listStudyNotes' : ActorMethod<[], Array<StudyNote>>,
  'searchStudyNotesByKeyword' : ActorMethod<[string], Array<StudyNote>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];