/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Document = IDL.Record({
  'id' : IDL.Nat,
  'requiredDocuments' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'processSteps' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'estimatedTime' : IDL.Text,
  'feesInfo' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'pricingInfo' : IDL.Text,
  'requiredDocuments' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'processSteps' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'timeline' : IDL.Text,
});
export const StudyNote = IDL.Record({
  'id' : IDL.Nat,
  'keySections' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'notesContent' : IDL.Text,
  'subject' : IDL.Text,
  'syllabusOutline' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterDocumentsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'filterServicesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getDocumentById' : IDL.Func([IDL.Nat], [Document], ['query']),
  'getServiceById' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getStudyNoteById' : IDL.Func([IDL.Nat], [StudyNote], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'listStudyNotes' : IDL.Func([], [IDL.Vec(StudyNote)], ['query']),
  'searchStudyNotesByKeyword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudyNote)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'requiredDocuments' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'processSteps' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'estimatedTime' : IDL.Text,
    'feesInfo' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'pricingInfo' : IDL.Text,
    'requiredDocuments' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'processSteps' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'timeline' : IDL.Text,
  });
  const StudyNote = IDL.Record({
    'id' : IDL.Nat,
    'keySections' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'notesContent' : IDL.Text,
    'subject' : IDL.Text,
    'syllabusOutline' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'filterDocumentsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'filterServicesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getDocumentById' : IDL.Func([IDL.Nat], [Document], ['query']),
    'getServiceById' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getStudyNoteById' : IDL.Func([IDL.Nat], [StudyNote], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'listStudyNotes' : IDL.Func([], [IDL.Vec(StudyNote)], ['query']),
    'searchStudyNotesByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudyNote)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };