/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Service {
    id: bigint;
    pricingInfo: string;
    requiredDocuments: Array<string>;
    name: string;
    description: string;
    processSteps: Array<string>;
    category: string;
    timeline: string;
}
export interface StudyNote {
    id: bigint;
    keySections: Array<string>;
    title: string;
    notesContent: string;
    subject: string;
    syllabusOutline: Array<string>;
    description: string;
}
export interface Document {
    id: bigint;
    requiredDocuments: Array<string>;
    name: string;
    description: string;
    processSteps: Array<string>;
    category: string;
    estimatedTime: string;
    feesInfo: string;
}
export interface backendInterface {
    filterDocumentsByCategory(category: string): Promise<Array<Document>>;
    filterServicesByCategory(category: string): Promise<Array<Service>>;
    getDocumentById(id: bigint): Promise<Document>;
    getServiceById(id: bigint): Promise<Service>;
    getStudyNoteById(id: bigint): Promise<StudyNote>;
    listDocuments(): Promise<Array<Document>>;
    listServices(): Promise<Array<Service>>;
    listStudyNotes(): Promise<Array<StudyNote>>;
    searchStudyNotesByKeyword(keyword: string): Promise<Array<StudyNote>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async filterDocumentsByCategory(arg0: string): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDocumentsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDocumentsByCategory(arg0);
            return result;
        }
    }
    async filterServicesByCategory(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterServicesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterServicesByCategory(arg0);
            return result;
        }
    }
    async getDocumentById(arg0: bigint): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentById(arg0);
            return result;
        }
    }
    async getServiceById(arg0: bigint): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceById(arg0);
            return result;
        }
    }
    async getStudyNoteById(arg0: bigint): Promise<StudyNote> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyNoteById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyNoteById(arg0);
            return result;
        }
    }
    async listDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments();
            return result;
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return result;
        }
    }
    async listStudyNotes(): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudyNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudyNotes();
            return result;
        }
    }
    async searchStudyNotesByKeyword(arg0: string): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudyNotesByKeyword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudyNotesByKeyword(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
